# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 李大夫——专治疑难杂症
email: 20476617@qq.com
description: > # this means to ignore newlines until "baseurl:"
  这个人很懒！
baseurl: "" # the subpath of your site, e.g. /blog
encoding: utf-8
url: "http://www.mrsan.cn" # the base hostname & protocol for your site
twitter_username: Doctor__li
github_username:  mrskylee

# Build settings
markdown: kramdown
